#!/bin/bash
set -eu

safe gen -l 16 ${CREDENTIALS}/containers username
safe gen       ${CREDENTIALS}/containers password
safe set       ${CREDENTIALS}/containers json@${RAWJSONFILE}
safe set       ${CREDENTIALS}/containers yaml@${YAMLFILE}

exit 0
