---
meta:
  size: default
  default:
    az: z1
  service:
    username: (( vault $CREDENTIALS "/containers:username" ))
    password: (( vault $CREDENTIALS "/containers:password" ))

releases:
  - name:    containers
    version: 1.3.1
    url:     https://github.com/jhunt/containers-boshrelease/releases/download/v1.3.1/containers-1.3.1.tgz
    sha1:    ec6945e71aff8d6e7d37f425702713f3ad9227a5

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

instance_groups:
  - name: containers
    instances: 1
    azs: [(( grab meta.az || meta.default.az ))]
    networks: [name: (( grab meta.net ))]
    stemcell: default

    vm_type: (( grab meta.size ))
    persistent_disk: (( grab meta.disk ))

    jobs:
      - name:    docker
        release: containers
        properties:
          container:
            config:
              listen_addresses: 0.0.0.0
